<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "dto_mapper"
 *
 * Auto generated by Extension Builder 2014-09-18
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Dto Mapper',
	'description' => 'A Dto Mapper',
	'category' => 'service',
	'author' => 'Martin Sonnenholzer',
	'author_email' => 'martin.sonnenholzer@googlemail.com',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.9.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);